version: 2

sources:
  - name: dbt_big
    database: ardent-depth-399309 # This should be your GCP project ID from Image 2
    schema: dbt_big            # This is your BigQuery dataset name from Image 2
    tables:
      - name: shopping_trends